language: php

matrix:
  include:
    - php: 8.0
      env: ILLUMINATE_VERSION=9.*
php:
  - 8.0

sudo: false

before_install:
  - composer require "illuminate/support:${ILLUMINATE_VERSION}" --no-update

install: composer update --prefer-source --no-interaction --dev

script: vendor/bin/phpunit --testdox
